//
// DuoCode.Helpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//
// Generated by DuoCode Compiler 0.3.878.0 BETA
//
(function DuoCode_Helpers() {
"use strict";
var $asm = {
    fullName: "DuoCode.Helpers",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() {
        return [new System.Reflection.AssemblyTitleAttribute.ctor("DuoCode.JQuery"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), 
            new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), 
            new System.Reflection.AssemblyProductAttribute.ctor("DuoCode.JQuery"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9 TheHat 2015"), 
            new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), 
            new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), 
            new DuoCode.Runtime.CompilerAttribute.ctor("0.3.878.0 BETA")];
    }
};
var $g = (typeof(global) !== "undefined" ? global : window);
var DuoCode = $g.DuoCode = $g.DuoCode || {};
DuoCode.Helpers = DuoCode.Helpers || {};
var $d = DuoCode.Runtime;
$d.$assemblies["DuoCode.Helpers"] = $asm;
DuoCode.Helpers.Jsonp = $d.declare("DuoCode.Helpers.Jsonp", System.Object, 0, $asm, function($t, $p) {
    $t.cctor = function() {
        $t._random = new System.Random.ctor();
    };
    $t.Request = function Jsonp_Request(TRequest, options) {
        options.get_BeforeRequest()();

        var script = document.createElement("script");

        var callbackName = "jsonp_callback_" + $d.toString($t()._random.Next());

        script.src = options.get_Url() + (options.get_Url().Contains("?") ? "&" : "?") + "callback=" + callbackName;
        script.onerror = $d.delegate(function(e) {
            options.OnError(e);
            DuoCode.Helpers.WindowExtensions.Eval(window, String.Format("delete window['{0}'];", $d.array(System.Object, 
                [callbackName])));
            return null;
        }, this);

        (window)[callbackName] = $d.cast(($d.delegate(function(data) {
            DuoCode.Helpers.WindowExtensions.Eval(window, String.Format("delete window['{0}'];", $d.array(System.Object, 
                [callbackName])));
            document.body.removeChild(script);

            var result = DuoCode.Helpers.JsObjectExtensions.Cast(TRequest, data);

            options.get_OnSuccess()(result);
        }, this)), System.Action$1(Object));

        document.body.appendChild(script);
    };
});
DuoCode.Helpers.IDeserializable$1 = $d.declare("DuoCode.Helpers.IDeserializable`1", null, 322, $asm, 
    function($t, $p, T) {}, ["T"]);
DuoCode.Helpers.Deserializer$1 = $d.declare("DuoCode.Helpers.Deserializer`1", System.Object, 256, $asm, 
    function($t, $p, T) {
        $t.$intfs = function() { return [DuoCode.Helpers.IDeserializable$1(T)]; };
        $t.ctor = function Deserializer$1() {
            $t.$baseType.ctor.call(this);
        };
    }, ["T"]);
DuoCode.Helpers.Ajax$2 = $d.declare("DuoCode.Helpers.Ajax`2", System.Object, 256, $asm, function($t, $p, TResponse, TDeserializer) {
    $t.cctor = function() {
        $t.$DefaultOnDeserializationException$k__BackingField = null;
        $t.$DefaultOnSuccess$k__BackingField = null;
        $t().set_DefaultOnDeserializationException($d.delegate(function(e, responseText, exception) {
            console.log("Deserialization error: " + responseText);
        }, this));

        $t().set_DefaultOnSuccess($d.delegate(function(e, response) {
            console.log(response);
        }, this));
    };
    $t.get_DefaultOnDeserializationException = function Ajax$2_get_DefaultOnDeserializationException() { return $t().$DefaultOnDeserializationException$k__BackingField; };
    $t.set_DefaultOnDeserializationException = function Ajax$2_set_DefaultOnDeserializationException(value) { $t().$DefaultOnDeserializationException$k__BackingField = value;return value; };
    $t.get_DefaultOnSuccess = function Ajax$2_get_DefaultOnSuccess() { return $t().$DefaultOnSuccess$k__BackingField; };
    $t.set_DefaultOnSuccess = function Ajax$2_set_DefaultOnSuccess(value) { $t().$DefaultOnSuccess$k__BackingField = value;return value; };
    $t.DefaultOnError = function Ajax$2_DefaultOnError(e, xmlHttpRequest) {
        window.alert(String.Format("Error with status {0}: {1}.", $d.array(System.Object, [xmlHttpRequest.status, 
            xmlHttpRequest.statusText])));
    };
    $t.Request$1 = function Ajax$2_Request(method, url, onSuccess, onDeserializationException, onError, beforeRequest) {
        onSuccess = onSuccess || $t().get_DefaultOnSuccess();
        onDeserializationException = onDeserializationException || $t().get_DefaultOnDeserializationException();
        onError = onError || $d.delegate(DuoCode.Helpers.Ajax$2(TResponse, TDeserializer).DefaultOnError);

        var xmlHttpRequest = new XMLHttpRequest();
        xmlHttpRequest.open($d.boxEnum(DuoCode.Helpers.Method, method), url, true);

        xmlHttpRequest.onreadystatechange = $d.delegate(function(e) {
            if (xmlHttpRequest.readyState == 4 /* AjaxRequestReadyState.ResponseReady */) {
                if (xmlHttpRequest.status != 200)
                    onError(e, xmlHttpRequest);

                var result = DuoCode.Helpers.Ajax$2(TResponse, TDeserializer).Deserialize(onDeserializationException, 
                    xmlHttpRequest.responseText, e);
                onSuccess(e, result);

                return null;
            }

            return null;
        }, this);

        if (beforeRequest != null)
            beforeRequest();

        xmlHttpRequest.send();
    };
    $t.Deserialize = function Ajax$2_Deserialize(onDeserializationException, responseText, e) {
        var deserializer = new TDeserializer.ctor();
        var result = $d.default(TResponse);
        try {
            result = deserializer.Deserialize(responseText);
        }
        catch ($e) {
            $e = System.Exception.Wrap($e);
            if ($e instanceof DuoCode.Helpers.DeserializationException) {
                onDeserializationException(e, responseText, $e);
            }
            else
                throw $e;
        }

        return result;
    };
    $t.Request = function Ajax$2_Request(options) {
        DuoCode.Helpers.Ajax$2(TResponse, TDeserializer).Request$1(options.get_Method(), options.get_Url(), 
            options.get_OnSuccess(), options.get_OnDeserializationException(), options.OnError, options.get_BeforeRequest());
    };
}, ["TResponse", $d.declareTP("TDeserializer", DuoCode.Helpers.Deserializer$1)]);
DuoCode.Helpers.Ajax$1 = $d.declare("DuoCode.Helpers.Ajax`1", System.Object, 256, $asm, function($t, $p, TResponse) {
    $t.cctor = function() {
        $t.$DefaultOnDeserializationException$k__BackingField = null;
        $t.$DefaultOnSuccess$k__BackingField = null;
        $t().set_DefaultOnDeserializationException($d.delegate(function(e, responseText, exception) {
            console.log("Deserialization error: " + responseText);
        }, this));

        $t().set_DefaultOnSuccess($d.delegate(function(e, response) {
            console.log(response);
        }, this));
    };
    $t.get_DefaultOnDeserializationException = function Ajax$1_get_DefaultOnDeserializationException() { return $t().$DefaultOnDeserializationException$k__BackingField; };
    $t.set_DefaultOnDeserializationException = function Ajax$1_set_DefaultOnDeserializationException(value) { $t().$DefaultOnDeserializationException$k__BackingField = value;return value; };
    $t.get_DefaultOnSuccess = function Ajax$1_get_DefaultOnSuccess() { return $t().$DefaultOnSuccess$k__BackingField; };
    $t.set_DefaultOnSuccess = function Ajax$1_set_DefaultOnSuccess(value) { $t().$DefaultOnSuccess$k__BackingField = value;return value; };
    $t.DefaultOnError = function Ajax$1_DefaultOnError(e, xmlHttpRequest) {
        window.alert(String.Format("Error with status {0}: {1}.", $d.array(System.Object, [xmlHttpRequest.status, 
            xmlHttpRequest.statusText])));
    };
    $t.Request$1 = function Ajax$1_Request(method, url, onSuccess, onDeserializationException, onError, beforeRequest) {
        onSuccess = onSuccess || $t().get_DefaultOnSuccess();
        onDeserializationException = onDeserializationException || $t().get_DefaultOnDeserializationException();
        onError = onError || $d.delegate(DuoCode.Helpers.Ajax$1(TResponse).DefaultOnError);

        var xmlHttpRequest = new XMLHttpRequest();
        xmlHttpRequest.open($d.boxEnum(DuoCode.Helpers.Method, method), url, true);

        xmlHttpRequest.onreadystatechange = $d.delegate(function(e) {
            if (xmlHttpRequest.readyState == 4 /* AjaxRequestReadyState.ResponseReady */) {
                if (xmlHttpRequest.status != 200)
                    onError(e, xmlHttpRequest);

                var result = DuoCode.Helpers.Ajax$1(TResponse).Deserialize(onDeserializationException, 
                    xmlHttpRequest.responseText, e);
                onSuccess(e, result);

                return null;
            }

            return null;
        }, this);

        if (beforeRequest != null)
            beforeRequest();

        xmlHttpRequest.send();
    };
    $t.Deserialize = function Ajax$1_Deserialize(onDeserializationException, responseText, e) {
        var deserializer = new (DuoCode.Helpers.JsonDeserializer$1(TResponse).ctor)();
        var result = $d.default(TResponse);
        try {
            result = deserializer.Deserialize(responseText);
        }
        catch ($e) {
            $e = System.Exception.Wrap($e);
            if ($e instanceof DuoCode.Helpers.DeserializationException) {
                onDeserializationException(e, responseText, $e);
            }
            else
                throw $e;
        }

        return result;
    };
    $t.Request = function Ajax$1_Request(options) {
        DuoCode.Helpers.Ajax$1(TResponse).Request$1(options.get_Method(), options.get_Url(), options.get_OnSuccess(), 
            options.get_OnDeserializationException(), options.OnError, options.get_BeforeRequest());
    };
}, ["TResponse"]);
DuoCode.Helpers.JsonpOptions$1 = $d.declare("DuoCode.Helpers.JsonpOptions`1", System.Object, 256, $asm, 
    function($t, $p, TRequest) {
        $t.$ator = function() {
            this.OnError = null;
            this.$OnSuccess$k__BackingField = null;
            this.$BeforeRequest$k__BackingField = null;
            this.$Url$k__BackingField = null;
            this.$OnDeserializationException$k__BackingField = null;
        };
        $p.get_OnSuccess = function JsonpOptions$1_get_OnSuccess() { return this.$OnSuccess$k__BackingField; };
        $p.set_OnSuccess = function JsonpOptions$1_set_OnSuccess(value) { this.$OnSuccess$k__BackingField = value;return value; };
        $p.get_BeforeRequest = function JsonpOptions$1_get_BeforeRequest() { return this.$BeforeRequest$k__BackingField; };
        $p.set_BeforeRequest = function JsonpOptions$1_set_BeforeRequest(value) { this.$BeforeRequest$k__BackingField = value;return value; };
        $p.get_Url = function JsonpOptions$1_get_Url() { return this.$Url$k__BackingField; };
        $p.set_Url = function JsonpOptions$1_set_Url(value) { this.$Url$k__BackingField = value;return value; };
        $p.get_OnDeserializationException = function JsonpOptions$1_get_OnDeserializationException() { return this.$OnDeserializationException$k__BackingField; };
        $p.set_OnDeserializationException = function JsonpOptions$1_set_OnDeserializationException(value) { this.$OnDeserializationException$k__BackingField = value;return value; };
        $t.ctor = function JsonpOptions$1() {
            $t.$baseType.ctor.call(this);
            this.OnError = $d.delegate(function(e) {}, this);
            this.set_OnSuccess($d.delegate(function(t) {}, this));
            this.set_BeforeRequest($d.delegate(function() {}, this));
            this.set_OnDeserializationException($d.delegate(function(data, exception) {
                console.log(String.Format("Unable to deserialize: {0}. Data: {1}", $d.array(System.Object, 
                    [exception.get_Message(), data])));
            }, this));
        };
        $t.ctor.prototype = $p;
    }, ["TRequest"]);
DuoCode.Helpers.AjaxOptions$1 = $d.declare("DuoCode.Helpers.AjaxOptions`1", System.Object, 256, $asm, 
    function($t, $p, T) {
        $t.$ator = function() {
            this.OnError = null;
            this.$OnSuccess$k__BackingField = null;
            this.$BeforeRequest$k__BackingField = null;
            this.$Url$k__BackingField = null;
            this.$Method$k__BackingField = 0 /* Method */;
            this.$OnDeserializationException$k__BackingField = null;
        };
        $t.ctor = function AjaxOptions$1() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $p.get_OnSuccess = function AjaxOptions$1_get_OnSuccess() { return this.$OnSuccess$k__BackingField; };
        $p.set_OnSuccess = function AjaxOptions$1_set_OnSuccess(value) { this.$OnSuccess$k__BackingField = value;return value; };
        $p.get_BeforeRequest = function AjaxOptions$1_get_BeforeRequest() { return this.$BeforeRequest$k__BackingField; };
        $p.set_BeforeRequest = function AjaxOptions$1_set_BeforeRequest(value) { this.$BeforeRequest$k__BackingField = value;return value; };
        $p.get_Url = function AjaxOptions$1_get_Url() { return this.$Url$k__BackingField; };
        $p.set_Url = function AjaxOptions$1_set_Url(value) { this.$Url$k__BackingField = value;return value; };
        $p.get_Method = function AjaxOptions$1_get_Method() { return this.$Method$k__BackingField; };
        $p.set_Method = function AjaxOptions$1_set_Method(value) { this.$Method$k__BackingField = value;return value; };
        $p.get_OnDeserializationException = function AjaxOptions$1_get_OnDeserializationException() { return this.$OnDeserializationException$k__BackingField; };
        $p.set_OnDeserializationException = function AjaxOptions$1_set_OnDeserializationException(value) { this.$OnDeserializationException$k__BackingField = value;return value; };
    }, ["T"]);
DuoCode.Helpers.AjaxRequestReadyState = $d.declareEnum("DuoCode.Helpers.AjaxRequestReadyState", 44, $asm, 
    257, ["RequestNotInitialized", "ServerConnectionEstablished", "RequestReceived", "ProcessingRequest", 
        "ResponseReady"], [0, 1, 2, 3, 4]);
DuoCode.Helpers.Md5HashInfo = $d.declare("DuoCode.Helpers.Md5HashInfo", System.Object, 0, $asm, function($t, $p) {
    $t.$typeInfo = function(t, p) { return [1, null, [["get_Md5Hash", p.get_Md5Hash, 6], ["set_Md5Hash", p.set_Md5Hash, 6], ["get_Text", p.get_Text, 6], ["set_Text", p.set_Text, 6], ["Foo", p.Foo, 6]], [["ctor", t.ctor, 6]], [["Md5Hash", 20, ["get_Md5Hash", p.get_Md5Hash, 6], ["set_Md5Hash", p.set_Md5Hash, 6], null, [new DuoCode.Helpers.JsonNameAttribute.ctor("md5")]], ["Text", 20, ["get_Text", p.get_Text, 6], ["set_Text", p.set_Text, 6], null, [new DuoCode.Helpers.JsonNameAttribute.ctor("original")]]]]; };
    $t.$ator = function() {
        this.$Md5Hash$k__BackingField = null;
        this.$Text$k__BackingField = null;
    };
    $t.ctor = function Md5HashInfo() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_Md5Hash = function Md5HashInfo_get_Md5Hash() { return this.$Md5Hash$k__BackingField; };
    $p.set_Md5Hash = function Md5HashInfo_set_Md5Hash(value) { this.$Md5Hash$k__BackingField = value;return value; };
    $p.get_Text = function Md5HashInfo_get_Text() { return this.$Text$k__BackingField; };
    $p.set_Text = function Md5HashInfo_set_Text(value) { this.$Text$k__BackingField = value;return value; };
    $p.Foo = function Md5HashInfo_Foo() {
        console.log(String.Format("text: {0}\nmd5: {1}", $d.array(System.Object, [this.get_Text(), this.get_Md5Hash()])));
    };
});
DuoCode.Helpers.Color = $d.declare("DuoCode.Helpers.Color", null, 62, $asm, function($t, $p) {
    $t.cctor = function() {
        $t.Violet = new DuoCode.Helpers.Color.ctor$2(204, 50, 206);
        $t.White = new DuoCode.Helpers.Color.ctor$1(1, 1, 1);
        $t.Grey = new DuoCode.Helpers.Color.ctor$1(0.5, 0.5, 0.5);
        $t.Black = new DuoCode.Helpers.Color.ctor$1(0, 0, 0);
        $t.Background = $t().Black;
        $t.DefaultColor = $t().Black;
    };
    $t.ctor = function Color() {
        this.R = 0;
        this.G = 0;
        this.B = 0;
    };
    $t.ctor.prototype = $p;
    $t.ctor$1 = function Color(r, g, b) {
        this.R = r;
        this.G = g;
        this.B = b;
    };
    $t.ctor$1.prototype = $p;
    $t.ctor$2 = function Color(r, g, b) {
        $t.ctor$1.call(this, DuoCode.Helpers.Color.FromByte(r), DuoCode.Helpers.Color.FromByte(g), DuoCode.Helpers.Color.FromByte(b));
    };
    $t.ctor$2.prototype = $p;
    $t.op_Multiply$1 = function Color_op_Multiply$1(k, v) {
        return new DuoCode.Helpers.Color.ctor$1(k * v.R, k * v.G, k * v.B);
    };
    $t.op_Addition = function Color_op_Addition(v1, v2) {
        return new DuoCode.Helpers.Color.ctor$1(v1.R + v2.R, v1.G + v2.G, v1.B + v2.B);
    };
    $t.op_Multiply = function Color_op_Multiply(v1, v2) {
        return new DuoCode.Helpers.Color.ctor$1(v1.R * v2.R, v1.G * v2.G, v1.B * v2.B);
    };
    $t.ToByte = function Color_ToByte(value) {
        value = value > 1 ? 1 : value;
        return (System.Math.Floor$1(value * 255 /* Byte.MaxValue */) | 0);
    };
    $t.FromByte = function Color_FromByte(value) {
        if (value > 255 /* Byte.MaxValue */)
            value = 255 /* Byte.MaxValue */;

        if (value < 0)
            value = 0;

        return value / 255 /* Byte.MaxValue */;
    };
    $p.ToString = function Color_ToString() {
        return String.Format("rgb({0},{1},{2})", $d.array(System.Object, [DuoCode.Helpers.Color.ToByte(this.R), 
            DuoCode.Helpers.Color.ToByte(this.G), DuoCode.Helpers.Color.ToByte(this.B)]));
    };
});
DuoCode.Helpers.JsonDeserializer$1 = $d.declare("DuoCode.Helpers.JsonDeserializer`1", DuoCode.Helpers.Deserializer$1, 
    768, $asm, function($t, $p, T) {
        $t.$intfs = function() { return [DuoCode.Helpers.IDeserializable$1(T)]; };
        $t.ctor = function JsonDeserializer$1() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $p.GetObject = function JsonDeserializer$1_GetObject() {
            throw new System.InvalidOperationException.ctor();
        };
        $p.Deserialize = function JsonDeserializer$1_Deserialize(source) {
            var jsObject = (new JSON().parse(source));
            return DuoCode.Helpers.JsObjectExtensions.Cast(T, jsObject);
        };
        $p.DuoCode$Helpers$IDeserializable$1$Deserialize = $p.Deserialize;
    }, ["T"]);
DuoCode.Helpers.JsonNameAttribute = $d.declare("DuoCode.Helpers.JsonNameAttribute", System.Attribute, 
    0, $asm, function($t, $p) {
        $t.$ator = function() {
            this.$Name$k__BackingField = null;
        };
        $p.get_Name = function JsonNameAttribute_get_Name() { return this.$Name$k__BackingField; };
        $p.set_Name = function JsonNameAttribute_set_Name(value) { this.$Name$k__BackingField = value;return value; };
        $t.ctor = function JsonNameAttribute(name) {
            $t.$baseType.ctor.call(this);
            this.set_Name(name);
        };
        $t.ctor.prototype = $p;
    });
DuoCode.Helpers.CssStyleDeclarationExtensions = $d.declare("DuoCode.Helpers.CssStyleDeclarationExtensions", 
    System.Object, 0, $asm, function($t, $p) {
        $t.AsDouble = function CssStyleDeclarationExtensions_AsDouble(source, getter) {
            return getter(source) * 1;
        };
        $t.AsInt32 = function CssStyleDeclarationExtensions_AsInt32(source, getter) {
            return getter(source) * 1;
        };
    });
DuoCode.Helpers.JsObjectExtensions = $d.declare("DuoCode.Helpers.JsObjectExtensions", System.Object, 
    0, $asm, function($t, $p) {
        $t.Cast = function JsObjectExtensions_Cast(T, jsObject) {
            var result = new T.ctor();
            for (var $i = 0, $a = $d.typeOf(T).GetProperties(), $length = $a.length; $i != $length; $i++) {
                var propertyInfo = $a[$i];
                var jsAttributes = propertyInfo.GetCustomAttributes$1($d.typeOf(DuoCode.Helpers.JsonNameAttribute), 
                    false);
                if (jsAttributes.get_Count() > 0) {
                    propertyInfo.SetValue(result, jsObject[jsAttributes[0].get_Name()]);
                }
            }

            return result;
        };
    });
DuoCode.Helpers.WindowExtensions = $d.declare("DuoCode.Helpers.WindowExtensions", System.Object, 0, $asm, 
    function($t, $p) {
        $t.Eval = function WindowExtensions_Eval(window, code) {
            if (window == null)
                throw new System.ArgumentNullException.ctor$1("window");
            if (String.IsNullOrEmpty(code))
                throw new System.ArgumentNullException.ctor$1("code");

            (window).eval(code);
        };
    });
DuoCode.Helpers.HtmlElementExtensions = $d.declare("DuoCode.Helpers.HtmlElementExtensions", System.Object, 
    0, $asm, function($t, $p) {
        $t.cctor = function() {
            $t.MillisecondsBetweenSteps = 40;
        };
        $t.Fade = function HtmlElementExtensions_Fade(element, fadingTime, initialOpacity) {
            if (fadingTime.get_TotalMilliseconds() <= 0.1) {
                element.style.opacity = "0";
                element.style.display = "none";

                return;
            }

            if (element.style.opacity <= 0) {
                element.style.display = "none";
                return;
            }

            var shadeStep = initialOpacity / (fadingTime.get_TotalMilliseconds() / 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);

            element.style.opacity = (DuoCode.Helpers.CssStyleDeclarationExtensions.AsDouble(element.style, 
                $d.delegate(function(s) {
                    return s.opacity;
                }, this)) - shadeStep).ToString();

            window.setTimeout(($d.delegate(function() {
                DuoCode.Helpers.HtmlElementExtensions.Fade(element, fadingTime, initialOpacity);
            }, this)), 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);
        };
        $t.Show = function HtmlElementExtensions_Show(element, showingTime, initialOpacity, display) {
            if (showingTime.get_TotalMilliseconds() <= 0.1) {
                element.style.opacity = "1";
                element.style.display = display || "block";

                return;
            }

            if (element.style.opacity <= 0)
                element.style.opacity = "0";

            if (element.style.opacity > 0)
                element.style.display = display || "block";

            if (element.style.opacity >= 1)
                return;

            var shadeStep = (1 - initialOpacity) / (showingTime.get_TotalMilliseconds() / 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);

            // BUG As<double> is string
            element.style.opacity = (shadeStep + DuoCode.Helpers.CssStyleDeclarationExtensions.AsDouble(element.style, 
                $d.delegate(function(s) {
                    return s.opacity;
                }, this))).ToString();

            window.setTimeout(($d.delegate(function() {
                DuoCode.Helpers.HtmlElementExtensions.Show(element, showingTime, initialOpacity, null);
            }, this)), 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);
        };
    });
DuoCode.Helpers.JQueryObjectExtensions = $d.declare("DuoCode.Helpers.JQueryObjectExtensions", System.Object, 
    0, $asm, function($t, $p) {
        $t.FadeOut = function JQueryObjectExtensions_FadeOut(source, duration, onComplete) {
            return source.fadeOut(duration.get_TotalMilliseconds(), onComplete);
        };
        $t.FadeIn = function JQueryObjectExtensions_FadeIn(source, duration, onComplete) {
            return source.fadeIn(duration.get_TotalMilliseconds(), onComplete);
        };
    });
DuoCode.Helpers.VanillaJQueryObject = $d.declare("DuoCode.Helpers.VanillaJQueryObject", System.Collections.Generic.List$1(HTMLElement), 
    0, $asm, function($t, $p) {
        $t.$intfs = function() { return [System.Collections.Generic.IList$1(HTMLElement), System.Collections.Generic.ICollection$1(HTMLElement), System.Collections.Generic.IReadOnlyList$1(HTMLElement), System.Collections.Generic.IReadOnlyCollection$1(HTMLElement), System.Collections.Generic.IEnumerable$1(HTMLElement), System.Collections.IList, System.Collections.ICollection, System.Collections.IEnumerable]; };
        $t.ctor = function VanillaJQueryObject() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $t.ctor$2 = function VanillaJQueryObject(elements) {
            $t.ctor.call(this);
            var $iter = elements;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                this.Add(element);
            }
        };
        $t.ctor$2.prototype = $p;
        $t.ctor$1 = function VanillaJQueryObject(elements) {
            $t.ctor$2.call(this, System.Linq.Enumerable.ToList(HTMLElement, elements));
        };
        $t.ctor$1.prototype = $p;
        $p.Css = function VanillaJQueryObject_Css(setter) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                setter(element.style);
            }

            return this;
        };
        $p.Attr$1 = function VanillaJQueryObject_Attr(attributeName, valueBuilder) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                var value = element.getAttribute(attributeName);
                element.setAttribute(attributeName, valueBuilder(value));
            }

            return this;
        };
        $p.Attr$2 = function VanillaJQueryObject_Attr(attributeName, value) {
            return this.Attr$1(attributeName, $d.delegate(function(v) {
                return value;
            }, this));
        };
        $p.Attr = function VanillaJQueryObject_Attr(attributeName) {
            return System.Linq.Enumerable.Any(HTMLElement, this) ? this.get_Item(0).getAttribute(attributeName) : null;
        };
        $p.Text = function VanillaJQueryObject_Text(text) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                element.innerText = text;
            }

            return this;
        };
        $p.Html = function VanillaJQueryObject_Html(html, evaluateScripts) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                element.innerHTML = html;
                if (!evaluateScripts)
                    continue;

                for (var i = 0; i < element.children.length; i++) {
                    var child = $d.as(element.children[i], HTMLScriptElement);
                    if (child != null)
                        (window).eval(child.innerText);
                }
            }

            return this;
        };
        $p.AddClass = function VanillaJQueryObject_AddClass(className) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                if (!element.classList.contains(className))
                    element.classList.add(className);
            }

            return this;
        };
        $p.RemoveClass = function VanillaJQueryObject_RemoveClass(className) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                if (element.classList.contains(className))
                    element.classList.remove(className);
            }

            return this;
        };
        $p.ToggleClass = function VanillaJQueryObject_ToggleClass(className) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                if (element.classList.contains(className))
                    element.classList.remove(className);
                else
                    element.classList.add(className);
            }

            return this;
        };
        $p.WithClass = function VanillaJQueryObject_WithClass(className) {
            return new DuoCode.Helpers.VanillaJQueryObject.ctor$2(System.Linq.Enumerable.Where(HTMLElement, 
                this, $d.delegate(function(e) {
                    return e.classList.contains(className);
                }, this)));
        };
        $p.WithoutClass = function VanillaJQueryObject_WithoutClass(className) {
            return new DuoCode.Helpers.VanillaJQueryObject.ctor$2(System.Linq.Enumerable.Where(HTMLElement, 
                this, $d.delegate(function(e) {
                    return !e.classList.contains(className);
                }, this)));
        };
        $p.AnyHasClass = function VanillaJQueryObject_AnyHasClass(className) {
            return System.Linq.Enumerable.Any$1(HTMLElement, this, $d.delegate(function(e) {
                return e.classList.contains(className);
            }, this));
        };
        $p.AllHasClass = function VanillaJQueryObject_AllHasClass(className) {
            return System.Linq.Enumerable.All(HTMLElement, this, $d.delegate(function(e) {
                return e.classList.contains(className);
            }, this));
        };
        $p.AnyDontHasClass = function VanillaJQueryObject_AnyDontHasClass(className) {
            return !this.AllHasClass(className);
        };
        $p.AllDontHasClass = function VanillaJQueryObject_AllDontHasClass(className) {
            return !this.AnyHasClass(className);
        };
        $p.Fade$1 = function VanillaJQueryObject_Fade(fadingTimeInMilliseconds) {
            return this.Fade(System.TimeSpan.FromMilliseconds(fadingTimeInMilliseconds));
        };
        $p.Fade = function VanillaJQueryObject_Fade(fadingTime) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                element.style.opacity = element.style.opacity || "1";
                DuoCode.Helpers.HtmlElementExtensions.Fade(element, fadingTime, element.style.opacity);
            }

            return this;
        };
        $p.Show$1 = function VanillaJQueryObject_Show(showingTimeInMilliseconds, display) {
            return this.Show(System.TimeSpan.FromMilliseconds(showingTimeInMilliseconds), null);
        };
        $p.Show = function VanillaJQueryObject_Show(showingTime, display) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                element.style.opacity = element.style.opacity || "0";
                DuoCode.Helpers.HtmlElementExtensions.Show(element, showingTime, element.style.opacity, 
                    display);
            }

            return this;
        };
    });
DuoCode.Helpers.VanillaJQuery = $d.declare("DuoCode.Helpers.VanillaJQuery", System.Object, 0, $asm, function($t, $p) {
    $t.cctor = function() {
        $t.Jquery = null;
        $t().Jquery = (window).jQuery;

        if ($t().Jquery == null)
            throw new System.InvalidOperationException.ctor$1("jQuery is not loaded");
    };
    $t.Get$1 = function VanillaJQuery_Get(selector) {
        var elements = $t().Jquery(selector);

        var result = new DuoCode.Helpers.VanillaJQueryObject.ctor();
        for (var $i = 0, $length = elements.length; $i != $length; $i++) {
            var element = elements[$i];
            result.Add(element);
        }

        return result;
    };
    $t.Get = function VanillaJQuery_Get(htmlElements) {
        return new DuoCode.Helpers.VanillaJQueryObject.ctor$1(htmlElements);
    };
});
DuoCode.Helpers.DeserializationException = $d.declare("DuoCode.Helpers.DeserializationException", System.Exception, 
    0, $asm, function($t, $p) {
        $t.ctor = function DeserializationException() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
    });
DuoCode.Helpers.HtmlElementDeserializer = $d.declare("DuoCode.Helpers.HtmlElementDeserializer", DuoCode.Helpers.Deserializer$1(HTMLElement), 
    0, $asm, function($t, $p) {
        $t.$intfs = function() { return [DuoCode.Helpers.IDeserializable$1(HTMLElement)]; };
        $t.ctor = function HtmlElementDeserializer() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $p.GetObject = function HtmlElementDeserializer_GetObject() {
            return document.createElement("div");
        };
        $p.Deserialize = function HtmlElementDeserializer_Deserialize(text) {
            var element = this.GetObject();
            element.innerHTML = text;

            return element;
        };
        $p.DuoCode$Helpers$IDeserializable$1$Deserialize = $p.Deserialize;
    });
DuoCode.Helpers.Method = $d.declareEnum("DuoCode.Helpers.Method", 45, $asm, 257, ["OPTIONS", "GET", "HEAD", 
    "POST", "PUT", "PATCH", "DELETE", "TRACE", "CONNECT"], [0, 1, 2, 3, 4, 5, 6, 7, 8]);
DuoCode.Helpers.Program = $d.declare("DuoCode.Helpers.Program", System.Object, 0, $asm, function($t, $p) {
    $t.RunJQuery = function Program_RunJQuery() {
        var a = $.fn.init("div");
        for (var $i = 0, $length = a.toArray().length; $i != $length; $i++) {
            var item = a.toArray()[$i];
            console.log($.fn.init(item).selector);
            item.innerHTML = "<p>asdasd</p>";
        }

        DuoCode.Helpers.JQueryObjectExtensions.FadeOut(a, System.TimeSpan.FromSeconds(4), null).html("LOL");
    };
    $t.RunAjax = function Program_RunAjax() {
        var el = $.fn.init(document.getElementById("content"));

        var options = (function() {
            var $obj = new (DuoCode.Helpers.AjaxOptions$1(HTMLElement).ctor)();
            $obj.set_Method(1 /* Method.GET */);
            $obj.set_Url("http://localhost:19308");
            $obj.set_BeforeRequest($d.delegate(function() {
                el.fadeOut(0);
            }, this));
            $obj.set_OnSuccess($d.delegate(function(e, element) {
                DuoCode.Helpers.JQueryObjectExtensions.FadeIn(el.html(element.innerHTML), System.TimeSpan.FromSeconds(4), 
                    null);
            }, this));
            return $obj;
        }).call(this);

        DuoCode.Helpers.Ajax$2(HTMLElement, DuoCode.Helpers.HtmlElementDeserializer).Request(options);
    };
    $t.RunAjaxJsonp = function Program_RunAjaxJsonp() {
        var input = $d.as(document.getElementById("inp"), HTMLInputElement);
        var button = document.getElementById("btn");

        button.onclick = $d.delegate(function(event) {
            var options = (function() {
                var $obj = new (DuoCode.Helpers.JsonpOptions$1(DuoCode.Helpers.Md5HashInfo).ctor)();
                $obj.set_Url(input == null ? String.Empty : input.value || String.Empty);
                $obj.set_OnSuccess($d.delegate(function(json) {
                    json.Foo();
                }, this));
                return $obj;
            }).call(this);

            DuoCode.Helpers.Jsonp.Request(DuoCode.Helpers.Md5HashInfo, options);

            return null;
        }, this);
    };
});
return $asm;
})();
//# sourceMappingURL=DuoCode.Helpers.js.map
