//
// DuoCode.JQuery, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//
// Generated by DuoCode Compiler 0.3.878.0 BETA
//
(function DuoCode_JQuery() {
"use strict";
var $asm = {
    fullName: "DuoCode.JQuery",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() {
        return [new System.Reflection.AssemblyTitleAttribute.ctor("DuoCode.JQuery"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), 
            new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), 
            new System.Reflection.AssemblyProductAttribute.ctor("DuoCode.JQuery"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9 TheHat 2015"), 
            new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), 
            new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), 
            new DuoCode.Runtime.CompilerAttribute.ctor("0.3.878.0 BETA")];
    }
};
var $g = (typeof(global) !== "undefined" ? global : window);
var DuoCode = $g.DuoCode = $g.DuoCode || {};
DuoCode.JQuery = DuoCode.JQuery || {};
var $d = DuoCode.Runtime;
$d.$assemblies["DuoCode.JQuery"] = $asm;
DuoCode.JQuery.Jsonp = $d.declare("DuoCode.JQuery.Jsonp", System.Object, 0, $asm, function($t, $p) {
    $t.cctor = function() {
        $t._random = new System.Random.ctor();
    };
    $t.Request = function Jsonp_Request(TRequest, options) {
        options.get_BeforeRequest()();

        var script = document.createElement("script");

        var callbackName = "jsonp_callback_" + $d.toString($t()._random.Next());

        script.src = options.get_Url() + (options.get_Url().Contains("?") ? "&" : "?") + "callback=" + callbackName;
        script.onerror = $d.delegate(function(e) {
            options.OnError(e);
            DuoCode.JQuery.WindowExtensions.Eval(window, String.Format("delete window['{0}'];", $d.array(System.Object, 
                [callbackName])));
            return null;
        }, this);

        (window)[callbackName] = $d.cast(($d.delegate(function(data) {
            DuoCode.JQuery.WindowExtensions.Eval(window, String.Format("delete window['{0}'];", $d.array(System.Object, 
                [callbackName])));
            document.body.removeChild(script);

            var result = DuoCode.JQuery.JsObjectExtensions.Cast(TRequest, data);

            options.get_OnSuccess()(result);
        }, this)), System.Action$1(Object));

        document.body.appendChild(script);
    };
});
DuoCode.JQuery.Deserializer$1 = $d.declare("DuoCode.JQuery.Deserializer`1", System.Object, 256, $asm, 
    function($t, $p, T) {
        $t.ctor = function Deserializer$1() {
            $t.$baseType.ctor.call(this);
        };
    }, ["T"]);
DuoCode.JQuery.Ajax$2 = $d.declare("DuoCode.JQuery.Ajax`2", System.Object, 256, $asm, function($t, $p, TResponse, TDeserializer) {
    $t.cctor = function() {
        $t.$DefaultOnDeserializationException$k__BackingField = null;
        $t.$DefaultOnSuccess$k__BackingField = null;
        $t().set_DefaultOnDeserializationException($d.delegate(function(e, responseText, exception) {
            console.log("Deserialization error: " + responseText);
        }, this));

        $t().set_DefaultOnSuccess($d.delegate(function(e, response) {
            console.log(response);
        }, this));
    };
    $t.get_DefaultOnDeserializationException = function Ajax$2_get_DefaultOnDeserializationException() { return $t().$DefaultOnDeserializationException$k__BackingField; };
    $t.set_DefaultOnDeserializationException = function Ajax$2_set_DefaultOnDeserializationException(value) { $t().$DefaultOnDeserializationException$k__BackingField = value;return value; };
    $t.get_DefaultOnSuccess = function Ajax$2_get_DefaultOnSuccess() { return $t().$DefaultOnSuccess$k__BackingField; };
    $t.set_DefaultOnSuccess = function Ajax$2_set_DefaultOnSuccess(value) { $t().$DefaultOnSuccess$k__BackingField = value;return value; };
    $t.DefaultOnError = function Ajax$2_DefaultOnError(e, xmlHttpRequest) {
        window.alert(String.Format("Error with status {0}: {1}.", $d.array(System.Object, [xmlHttpRequest.status, 
            xmlHttpRequest.statusText])));
    };
    $t.Request$1 = function Ajax$2_Request(method, url, onSuccess, onDeserializationException, onError, beforeRequest) {
        onSuccess = onSuccess || $t().get_DefaultOnSuccess();
        onDeserializationException = onDeserializationException || $t().get_DefaultOnDeserializationException();
        onError = onError || $d.delegate(DuoCode.JQuery.Ajax$2(TResponse, TDeserializer).DefaultOnError);

        var xmlHttpRequest = new XMLHttpRequest();
        xmlHttpRequest.open($d.boxEnum(DuoCode.Helpers.Method, method), url, true);

        xmlHttpRequest.onreadystatechange = $d.delegate(function(e) {
            if (xmlHttpRequest.readyState == 4 /* AjaxRequestReadyState.ResponseReady */) {
                if (xmlHttpRequest.status != 200)
                    onError(e, xmlHttpRequest);

                var result = DuoCode.JQuery.Ajax$2(TResponse, TDeserializer).Deserialize(onDeserializationException, 
                    xmlHttpRequest.responseText, e);
                onSuccess(e, result);

                return null;
            }

            return null;
        }, this);

        if (beforeRequest != null)
            beforeRequest();

        xmlHttpRequest.send();
    };
    $t.Deserialize = function Ajax$2_Deserialize(onDeserializationException, responseText, e) {
        var deserializer = new TDeserializer.ctor();
        var result = $d.default(TResponse);
        try {
            result = deserializer.Deserialize(responseText);
        }
        catch ($e) {
            $e = System.Exception.Wrap($e);
            if ($e instanceof DuoCode.JQuery.DeserializationException) {
                onDeserializationException(e, responseText, $e);
            }
            else
                throw $e;
        }

        return result;
    };
    $t.Request = function Ajax$2_Request(options) {
        DuoCode.JQuery.Ajax$2(TResponse, TDeserializer).Request$1(options.get_Method(), options.get_Url(), 
            options.get_OnSuccess(), options.get_OnDeserializationException(), options.OnError, options.get_BeforeRequest());
    };
}, ["TResponse", $d.declareTP("TDeserializer", DuoCode.JQuery.Deserializer$1)]);
DuoCode.JQuery.Ajax$1 = $d.declare("DuoCode.JQuery.Ajax`1", System.Object, 256, $asm, function($t, $p, TResponse) {
    $t.cctor = function() {
        $t.$DefaultOnDeserializationException$k__BackingField = null;
        $t.$DefaultOnSuccess$k__BackingField = null;
        $t().set_DefaultOnDeserializationException($d.delegate(function(e, responseText, exception) {
            console.log("Deserialization error: " + responseText);
        }, this));

        $t().set_DefaultOnSuccess($d.delegate(function(e, response) {
            console.log(response);
        }, this));
    };
    $t.get_DefaultOnDeserializationException = function Ajax$1_get_DefaultOnDeserializationException() { return $t().$DefaultOnDeserializationException$k__BackingField; };
    $t.set_DefaultOnDeserializationException = function Ajax$1_set_DefaultOnDeserializationException(value) { $t().$DefaultOnDeserializationException$k__BackingField = value;return value; };
    $t.get_DefaultOnSuccess = function Ajax$1_get_DefaultOnSuccess() { return $t().$DefaultOnSuccess$k__BackingField; };
    $t.set_DefaultOnSuccess = function Ajax$1_set_DefaultOnSuccess(value) { $t().$DefaultOnSuccess$k__BackingField = value;return value; };
    $t.DefaultOnError = function Ajax$1_DefaultOnError(e, xmlHttpRequest) {
        window.alert(String.Format("Error with status {0}: {1}.", $d.array(System.Object, [xmlHttpRequest.status, 
            xmlHttpRequest.statusText])));
    };
    $t.Request$1 = function Ajax$1_Request(method, url, onSuccess, onDeserializationException, onError, beforeRequest) {
        onSuccess = onSuccess || $t().get_DefaultOnSuccess();
        onDeserializationException = onDeserializationException || $t().get_DefaultOnDeserializationException();
        onError = onError || $d.delegate(DuoCode.JQuery.Ajax$1(TResponse).DefaultOnError);

        var xmlHttpRequest = new XMLHttpRequest();
        xmlHttpRequest.open($d.boxEnum(DuoCode.Helpers.Method, method), url, true);

        xmlHttpRequest.onreadystatechange = $d.delegate(function(e) {
            if (xmlHttpRequest.readyState == 4 /* AjaxRequestReadyState.ResponseReady */) {
                if (xmlHttpRequest.status != 200)
                    onError(e, xmlHttpRequest);

                var result = DuoCode.JQuery.Ajax$1(TResponse).Deserialize(onDeserializationException, 
                    xmlHttpRequest.responseText, e);
                onSuccess(e, result);

                return null;
            }

            return null;
        }, this);

        if (beforeRequest != null)
            beforeRequest();

        xmlHttpRequest.send();
    };
    $t.Deserialize = function Ajax$1_Deserialize(onDeserializationException, responseText, e) {
        var deserializer = new (DuoCode.JQuery.JsonDeserializer$1(TResponse).ctor)();
        var result = $d.default(TResponse);
        try {
            result = deserializer.Deserialize(responseText);
        }
        catch ($e) {
            $e = System.Exception.Wrap($e);
            if ($e instanceof DuoCode.JQuery.DeserializationException) {
                onDeserializationException(e, responseText, $e);
            }
            else
                throw $e;
        }

        return result;
    };
    $t.Request = function Ajax$1_Request(options) {
        DuoCode.JQuery.Ajax$1(TResponse).Request$1(options.get_Method(), options.get_Url(), options.get_OnSuccess(), 
            options.get_OnDeserializationException(), options.OnError, options.get_BeforeRequest());
    };
}, ["TResponse"]);
DuoCode.JQuery.JsonpOptions$1 = $d.declare("DuoCode.JQuery.JsonpOptions`1", System.Object, 256, $asm, 
    function($t, $p, TRequest) {
        $t.$ator = function() {
            this.OnError = null;
            this.$OnSuccess$k__BackingField = null;
            this.$BeforeRequest$k__BackingField = null;
            this.$Url$k__BackingField = null;
            this.$OnDeserializationException$k__BackingField = null;
        };
        $p.get_OnSuccess = function JsonpOptions$1_get_OnSuccess() { return this.$OnSuccess$k__BackingField; };
        $p.set_OnSuccess = function JsonpOptions$1_set_OnSuccess(value) { this.$OnSuccess$k__BackingField = value;return value; };
        $p.get_BeforeRequest = function JsonpOptions$1_get_BeforeRequest() { return this.$BeforeRequest$k__BackingField; };
        $p.set_BeforeRequest = function JsonpOptions$1_set_BeforeRequest(value) { this.$BeforeRequest$k__BackingField = value;return value; };
        $p.get_Url = function JsonpOptions$1_get_Url() { return this.$Url$k__BackingField; };
        $p.set_Url = function JsonpOptions$1_set_Url(value) { this.$Url$k__BackingField = value;return value; };
        $p.get_OnDeserializationException = function JsonpOptions$1_get_OnDeserializationException() { return this.$OnDeserializationException$k__BackingField; };
        $p.set_OnDeserializationException = function JsonpOptions$1_set_OnDeserializationException(value) { this.$OnDeserializationException$k__BackingField = value;return value; };
        $t.ctor = function JsonpOptions$1() {
            $t.$baseType.ctor.call(this);
            this.OnError = $d.delegate(function(e) {}, this);
            this.set_OnSuccess($d.delegate(function(t) {}, this));
            this.set_BeforeRequest($d.delegate(function() {}, this));
            this.set_OnDeserializationException($d.delegate(function(data, exception) {
                console.log(String.Format("Unable to deserialize: {0}. Data: {1}", $d.array(System.Object, 
                    [exception.get_Message(), data])));
            }, this));
        };
        $t.ctor.prototype = $p;
    }, ["TRequest"]);
DuoCode.JQuery.AjaxOptions$1 = $d.declare("DuoCode.JQuery.AjaxOptions`1", System.Object, 256, $asm, function($t, $p, T) {
    $t.$ator = function() {
        this.OnError = null;
        this.$OnSuccess$k__BackingField = null;
        this.$BeforeRequest$k__BackingField = null;
        this.$Url$k__BackingField = null;
        this.$Method$k__BackingField = 0 /* Method */;
        this.$OnDeserializationException$k__BackingField = null;
    };
    $t.ctor = function AjaxOptions$1() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_OnSuccess = function AjaxOptions$1_get_OnSuccess() { return this.$OnSuccess$k__BackingField; };
    $p.set_OnSuccess = function AjaxOptions$1_set_OnSuccess(value) { this.$OnSuccess$k__BackingField = value;return value; };
    $p.get_BeforeRequest = function AjaxOptions$1_get_BeforeRequest() { return this.$BeforeRequest$k__BackingField; };
    $p.set_BeforeRequest = function AjaxOptions$1_set_BeforeRequest(value) { this.$BeforeRequest$k__BackingField = value;return value; };
    $p.get_Url = function AjaxOptions$1_get_Url() { return this.$Url$k__BackingField; };
    $p.set_Url = function AjaxOptions$1_set_Url(value) { this.$Url$k__BackingField = value;return value; };
    $p.get_Method = function AjaxOptions$1_get_Method() { return this.$Method$k__BackingField; };
    $p.set_Method = function AjaxOptions$1_set_Method(value) { this.$Method$k__BackingField = value;return value; };
    $p.get_OnDeserializationException = function AjaxOptions$1_get_OnDeserializationException() { return this.$OnDeserializationException$k__BackingField; };
    $p.set_OnDeserializationException = function AjaxOptions$1_set_OnDeserializationException(value) { this.$OnDeserializationException$k__BackingField = value;return value; };
}, ["T"]);
DuoCode.JQuery.AjaxRequestReadyState = $d.declareEnum("DuoCode.JQuery.AjaxRequestReadyState", 44, $asm, 
    257, ["RequestNotInitialized", "ServerConnectionEstablished", "RequestReceived", "ProcessingRequest", 
        "ResponseReady"], [0, 1, 2, 3, 4]);
DuoCode.JQuery.Md5HashInfo = $d.declare("DuoCode.JQuery.Md5HashInfo", System.Object, 0, $asm, function($t, $p) {
    $t.$typeInfo = function(t, p) { return [1, null, [["get_Md5Hash", p.get_Md5Hash, 6], ["set_Md5Hash", p.set_Md5Hash, 6], ["get_Text", p.get_Text, 6], ["set_Text", p.set_Text, 6], ["Foo", p.Foo, 6]], [["ctor", t.ctor, 6]], [["Md5Hash", 20, ["get_Md5Hash", p.get_Md5Hash, 6], ["set_Md5Hash", p.set_Md5Hash, 6], null, [new DuoCode.JQuery.JsonNameAttribute.ctor("md5")]], ["Text", 20, ["get_Text", p.get_Text, 6], ["set_Text", p.set_Text, 6], null, [new DuoCode.JQuery.JsonNameAttribute.ctor("original")]]]]; };
    $t.$ator = function() {
        this.$Md5Hash$k__BackingField = null;
        this.$Text$k__BackingField = null;
    };
    $t.ctor = function Md5HashInfo() {
        $t.$baseType.ctor.call(this);
    };
    $t.ctor.prototype = $p;
    $p.get_Md5Hash = function Md5HashInfo_get_Md5Hash() { return this.$Md5Hash$k__BackingField; };
    $p.set_Md5Hash = function Md5HashInfo_set_Md5Hash(value) { this.$Md5Hash$k__BackingField = value;return value; };
    $p.get_Text = function Md5HashInfo_get_Text() { return this.$Text$k__BackingField; };
    $p.set_Text = function Md5HashInfo_set_Text(value) { this.$Text$k__BackingField = value;return value; };
    $p.Foo = function Md5HashInfo_Foo() {
        console.log(String.Format("text: {0}\nmd5: {1}", $d.array(System.Object, [this.get_Text(), this.get_Md5Hash()])));
    };
});
DuoCode.JQuery.DeserializationUtility = $d.declare("DuoCode.JQuery.DeserializationUtility", System.Object, 
    0, $asm, function($t, $p) {
        $t.ctor = function DeserializationUtility() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $t.Deserialize = function DeserializationUtility_Deserialize(TResponse, TDeserializer, source) {
            var deserializer = new TDeserializer.ctor();

            return deserializer.Deserialize(source);
        };
    });
DuoCode.JQuery.JsonDeserializer$1 = $d.declare("DuoCode.JQuery.JsonDeserializer`1", DuoCode.JQuery.Deserializer$1, 
    768, $asm, function($t, $p, T) {
        $t.ctor = function JsonDeserializer$1() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $p.GetObject = function JsonDeserializer$1_GetObject() {
            throw new System.InvalidOperationException.ctor();
        };
        $p.Deserialize = function JsonDeserializer$1_Deserialize(source) {
            var jsObject = (new JSON().parse(source));
            return DuoCode.JQuery.JsObjectExtensions.Cast(T, jsObject);
        };
    }, ["T"]);
DuoCode.JQuery.JsonNameAttribute = $d.declare("DuoCode.JQuery.JsonNameAttribute", System.Attribute, 0, 
    $asm, function($t, $p) {
        $t.$ator = function() {
            this.$Name$k__BackingField = null;
        };
        $p.get_Name = function JsonNameAttribute_get_Name() { return this.$Name$k__BackingField; };
        $p.set_Name = function JsonNameAttribute_set_Name(value) { this.$Name$k__BackingField = value;return value; };
        $t.ctor = function JsonNameAttribute(name) {
            $t.$baseType.ctor.call(this);
            this.set_Name(name);
        };
        $t.ctor.prototype = $p;
    });
DuoCode.JQuery.CssStyleDeclarationExtensions = $d.declare("DuoCode.JQuery.CssStyleDeclarationExtensions", 
    System.Object, 0, $asm, function($t, $p) {
        $t.AsDouble = function CssStyleDeclarationExtensions_AsDouble(source, getter) {
            return getter(source) * 1;
        };
        $t.AsInt32 = function CssStyleDeclarationExtensions_AsInt32(source, getter) {
            return getter(source) * 1;
        };
    });
DuoCode.JQuery.JsObjectExtensions = $d.declare("DuoCode.JQuery.JsObjectExtensions", System.Object, 0, 
    $asm, function($t, $p) {
        $t.Cast = function JsObjectExtensions_Cast(T, jsObject) {
            var result = new T.ctor();
            for (var $i = 0, $a = $d.typeOf(T).GetProperties(), $length = $a.length; $i != $length; $i++) {
                var propertyInfo = $a[$i];
                var jsAttributes = propertyInfo.GetCustomAttributes$1($d.typeOf(DuoCode.JQuery.JsonNameAttribute), 
                    false);
                if (jsAttributes.get_Count() > 0) {
                    propertyInfo.SetValue(result, jsObject[jsAttributes[0].get_Name()]);
                }
            }

            return result;
        };
    });
DuoCode.JQuery.WindowExtensions = $d.declare("DuoCode.JQuery.WindowExtensions", System.Object, 0, $asm, 
    function($t, $p) {
        $t.Eval = function WindowExtensions_Eval(window, code) {
            if (window == null)
                throw new System.ArgumentNullException.ctor$1("window");
            if (String.IsNullOrEmpty(code))
                throw new System.ArgumentNullException.ctor$1("code");

            (window).eval(code);
        };
    });
DuoCode.JQuery.HtmlElementExtensions = $d.declare("DuoCode.JQuery.HtmlElementExtensions", System.Object, 
    0, $asm, function($t, $p) {
        $t.cctor = function() {
            $t.MillisecondsBetweenSteps = 40;
        };
        $t.Fade = function HtmlElementExtensions_Fade(element, fadingTime, initialOpacity) {
            if (fadingTime.get_TotalMilliseconds() <= 0.1) {
                element.style.opacity = "0";
                element.style.display = "none";

                return;
            }

            if (element.style.opacity <= 0) {
                element.style.display = "none";
                return;
            }

            var shadeStep = initialOpacity / (fadingTime.get_TotalMilliseconds() / 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);

            element.style.opacity = (DuoCode.JQuery.CssStyleDeclarationExtensions.AsDouble(element.style, 
                $d.delegate(function(s) {
                    return s.opacity;
                }, this)) - shadeStep).ToString();

            window.setTimeout(($d.delegate(function() {
                DuoCode.JQuery.HtmlElementExtensions.Fade(element, fadingTime, initialOpacity);
            }, this)), 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);
        };
        $t.Show = function HtmlElementExtensions_Show(element, showingTime, initialOpacity, display) {
            if (showingTime.get_TotalMilliseconds() <= 0.1) {
                element.style.opacity = "1";
                element.style.display = display || "block";

                return;
            }

            if (element.style.opacity <= 0)
                element.style.opacity = "0";

            if (element.style.opacity > 0)
                element.style.display = display || "block";

            if (element.style.opacity >= 1)
                return;

            var shadeStep = (1 - initialOpacity) / (showingTime.get_TotalMilliseconds() / 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);

            // BUG As<double> is string
            element.style.opacity = (shadeStep + DuoCode.JQuery.CssStyleDeclarationExtensions.AsDouble(element.style, 
                $d.delegate(function(s) {
                    return s.opacity;
                }, this))).ToString();

            window.setTimeout(($d.delegate(function() {
                DuoCode.JQuery.HtmlElementExtensions.Show(element, showingTime, initialOpacity, null);
            }, this)), 40 /* HtmlElementExtensions.MillisecondsBetweenSteps */);
        };
    });
DuoCode.JQuery.JQueryObjectExtensions = $d.declare("DuoCode.JQuery.JQueryObjectExtensions", System.Object, 
    0, $asm, function($t, $p) {
        $t.FadeOut = function JQueryObjectExtensions_FadeOut(source, duration, onComplete) {
            return source.fadeOut(duration.get_TotalMilliseconds(), onComplete);
        };
        $t.FadeIn = function JQueryObjectExtensions_FadeIn(source, duration, onComplete) {
            return source.fadeIn(duration.get_TotalMilliseconds(), onComplete);
        };
    });
DuoCode.JQuery.AjaxDataType = $d.declareEnum("DuoCode.JQuery.AjaxDataType", 45, $asm, 257, ["xml", "html", 
    "script", "json", "jsonp", "text"], [0, 1, 2, 3, 4, 5]);
DuoCode.JQuery.AjaxErrorTextStatus = $d.declareEnum("DuoCode.JQuery.AjaxErrorTextStatus", 45, $asm, 257, 
    ["timeout", "error", "abort", "parsererror"], [0, 1, 2, 3]);
DuoCode.JQuery.AjaxSettings = $d.declare("DuoCode.JQuery.AjaxSettings", System.Object, 0, $asm, function($t, $p) {
    $t.$ator = function() {
        this.beforeSend = null;
        this.context = null;
        this.data = null;
        this.dataType = 0 /* AjaxDataType */;
        this.headers = null;
        this.async = false;
        this.cache = false;
        this.crossDomain = false;
        this.complete = null;
        this.error = null;
        this.success = null;
        this.password = null;
        this.timeout = null;
        this.type = null;
        this.url = null;
        this.global = false;
        this.username = null;
    };
    $t.ctor = function AjaxSettings() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_DataType = function AjaxSettings_get_DataType() {
        return this.dataType;
    };
    $p.set_DataType = function AjaxSettings_set_DataType(value) {
        this.dataType = value;
        return value;
    };
    $p.get_Timeout = function AjaxSettings_get_Timeout() {
        if (String.IsNullOrEmpty(this.timeout))
            throw new System.InvalidOperationException.ctor$1("Timeout was not set");

        var timeout = this.timeout;
        if (timeout != null)
            return System.TimeSpan.FromMilliseconds($d.nv(timeout));

        throw new System.InvalidOperationException.ctor$1("Timeout is invalid");
    };
    $p.set_Timeout = function AjaxSettings_set_Timeout(value) {
        this.timeout = value.get_TotalMilliseconds().ToString();
        return value;
    };
    $p.get_Method = function AjaxSettings_get_Method() {
        return $d.ncl(DuoCode.Helpers.StringExtensions.TryGet(DuoCode.Helpers.Method, this.type), 1 /* Method.GET */);
    };
    $p.set_Method = function AjaxSettings_set_Method(value) {
        this.type = $d.boxEnum(DuoCode.Helpers.Method, value).ToString();
        return value;
    };
    $p.get_Context = function AjaxSettings_get_Context() {
        return this.context;
    };
    $p.set_Context = function AjaxSettings_set_Context(value) {
        this.context = value;
        return value;
    };
    $p.get_IsAsync = function AjaxSettings_get_IsAsync() {
        return this.async;
    };
    $p.set_IsAsync = function AjaxSettings_set_IsAsync(value) {
        this.async = value;
        return value;
    };
    $p.get_IsCached = function AjaxSettings_get_IsCached() {
        return this.cache;
    };
    $p.set_IsCached = function AjaxSettings_set_IsCached(value) {
        this.cache = value;
        return value;
    };
    $p.get_BeforeSend = function AjaxSettings_get_BeforeSend() {
        return this.beforeSend;
    };
    $p.set_BeforeSend = function AjaxSettings_set_BeforeSend(value) {
        this.beforeSend = value;
        return value;
    };
    $p.get_OnComplete = function AjaxSettings_get_OnComplete() {
        return this.complete;
    };
    $p.set_OnComplete = function AjaxSettings_set_OnComplete(value) {
        this.complete = value;
        return value;
    };
    $p.get_IsCrossDomain = function AjaxSettings_get_IsCrossDomain() {
        return this.crossDomain;
    };
    $p.set_IsCrossDomain = function AjaxSettings_set_IsCrossDomain(value) {
        this.crossDomain = value;
        return value;
    };
    $p.get_Data = function AjaxSettings_get_Data() {
        return this.data;
    };
    $p.set_Data = function AjaxSettings_set_Data(value) {
        this.data = value;
        return value;
    };
    $p.get_OnError = function AjaxSettings_get_OnError() {
        return this.error;
    };
    $p.set_OnError = function AjaxSettings_set_OnError(value) {
        this.error = value;
        return value;
    };
    $p.get_UseGlobalAjaxEventHandlers = function AjaxSettings_get_UseGlobalAjaxEventHandlers() {
        return this.global;
    };
    $p.set_UseGlobalAjaxEventHandlers = function AjaxSettings_set_UseGlobalAjaxEventHandlers(value) {
        this.global = value;
        return value;
    };
    $p.get_Headers = function AjaxSettings_get_Headers() {
        return this.headers;
    };
    $p.set_Headers = function AjaxSettings_set_Headers(value) {
        this.headers = value;
        return value;
    };
    $p.get_Url = function AjaxSettings_get_Url() {
        return this.url;
    };
    $p.set_Url = function AjaxSettings_set_Url(value) {
        this.url = value;
        return value;
    };
    $p.get_Username = function AjaxSettings_get_Username() {
        return this.username;
    };
    $p.set_Username = function AjaxSettings_set_Username(value) {
        this.username = value;
        return value;
    };
    $p.get_Password = function AjaxSettings_get_Password() {
        return this.password;
    };
    $p.set_Password = function AjaxSettings_set_Password(value) {
        this.password = value;
        return value;
    };
});
DuoCode.JQuery.AjaxSettings$2 = $d.declare("DuoCode.JQuery.AjaxSettings`2", DuoCode.JQuery.AjaxSettings, 
    256, $asm, function($t, $p, TResponse, TDeserializer) {
        $t.$ator = function() {
            this.$OnDeserializationException$k__BackingField = null;
            this.$OnSuccess$k__BackingField = null;
        };
        $p.get_OnDeserializationException = function AjaxSettings$2_get_OnDeserializationException() { return this.$OnDeserializationException$k__BackingField; };
        $p.set_OnDeserializationException = function AjaxSettings$2_set_OnDeserializationException(value) { this.$OnDeserializationException$k__BackingField = value;return value; };
        $p.get_DataType = function AjaxSettings$2_get_DataType() {
            return 5 /* AjaxDataType.text */;
        };
        $p.set_DataType = function AjaxSettings$2_set_DataType(value) {
            return value;
        };
        $p.get_OnSuccess = function AjaxSettings$2_get_OnSuccess() { return this.$OnSuccess$k__BackingField; };
        $p.set_OnSuccess = function AjaxSettings$2_set_OnSuccess(value) { this.$OnSuccess$k__BackingField = value;return value; };
        $t.ctor = function AjaxSettings$2() {
            $t.$baseType.ctor.call(this);
            this.success = $d.delegate(function(data, textStatus, jqXHR) {
                var responseText = $d.as(data.ToString(), String);
                try {
                    var deserializedData = DuoCode.JQuery.DeserializationUtility.Deserialize(TResponse, 
                        TDeserializer, responseText);
                    this.get_OnSuccess()(deserializedData, textStatus, $d.as(jqXHR, DuoCode.JQuery.JqXHR$2(TResponse, 
                        TDeserializer)));
                }
                catch ($e) {
                    $e = System.Exception.Wrap($e);
                    if ($e instanceof DuoCode.JQuery.DeserializationException) {
                        this.get_OnDeserializationException()(responseText, $e);
                    }
                    else
                        throw $e;
                }

            }, this);
        };
        $t.ctor.prototype = $p;
    }, ["TResponse", $d.declareTP("TDeserializer", DuoCode.JQuery.Deserializer$1)]);
DuoCode.JQuery.AjaxSettings$1 = $d.declare("DuoCode.JQuery.AjaxSettings`1", DuoCode.JQuery.AjaxSettings$2, 
    768, $asm, function($t, $p, TResponse) {
        $t.ctor = function AjaxSettings$1() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
    }, ["TResponse"], [0, DuoCode.JQuery.JsonDeserializer$1]);
DuoCode.JQuery.DeserializationException = $d.declare("DuoCode.JQuery.DeserializationException", System.Exception, 
    0, $asm, function($t, $p) {
        $t.ctor = function DeserializationException() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
    });
DuoCode.JQuery.HtmlElementDeserializer = $d.declare("DuoCode.JQuery.HtmlElementDeserializer", DuoCode.JQuery.Deserializer$1(HTMLElement), 
    0, $asm, function($t, $p) {
        $t.ctor = function HtmlElementDeserializer() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $p.GetObject = function HtmlElementDeserializer_GetObject() {
            return document.createElement("div");
        };
        $p.Deserialize = function HtmlElementDeserializer_Deserialize(text) {
            var element = this.GetObject();
            element.innerHTML = text;

            return element;
        };
    });
DuoCode.JQuery.JqXHR = $d.declare("DuoCode.JQuery.JqXHR", XMLHttpRequest, 0, $asm, function($t, $p) {
    $t.$ator = function() {
        this.done = null;
        this.fail = null;
        this.$onreadystatechange$k__BackingField = null;
    };
    $t.ctor = function JqXHR() {
        $t.$baseType.ctor.call(this);
    };
    $p.get_onreadystatechange$1 = function JqXHR_get_onreadystatechange$1() { return this.$onreadystatechange$k__BackingField; };
    $p.set_onreadystatechange$1 = function JqXHR_set_onreadystatechange$1(value) { this.$onreadystatechange$k__BackingField = value;return value; };
    $p.get_OnDoneDynamic = function JqXHR_get_OnDoneDynamic() {
        return this.done;
    };
    $p.set_OnDoneDynamic = function JqXHR_set_OnDoneDynamic(value) {
        this.done = value;
        return value;
    };
    $p.get_OnFail = function JqXHR_get_OnFail() {
        return this.fail;
    };
    $p.set_OnFail = function JqXHR_set_OnFail(value) {
        this.fail = value;
        return value;
    };
});
DuoCode.JQuery.JqXHR$2 = $d.declare("DuoCode.JQuery.JqXHR`2", DuoCode.JQuery.JqXHR, 256, $asm, function($t, $p, TResponse, TDeserializer) {
    $t.$ator = function() {
        this.$OnDone$k__BackingField = null;
    };
    $p.get_OnDone = function JqXHR$2_get_OnDone() { return this.$OnDone$k__BackingField; };
    $p.set_OnDone = function JqXHR$2_set_OnDone(value) { this.$OnDone$k__BackingField = value;return value; };
    $t.ctor = function JqXHR$2() {
        $t.$baseType.ctor.call(this);
        this.set_OnDoneDynamic($d.delegate(function(data, textStatus, jqXHR) {
            var result = DuoCode.JQuery.DeserializationUtility.Deserialize(TResponse, TDeserializer, 
                this.responseText);
            this.get_OnDone()(result, textStatus, jqXHR);
        }, this));
    };
    $t.ctor.prototype = $p;
}, ["TResponse", $d.declareTP("TDeserializer", DuoCode.JQuery.Deserializer$1)]);
DuoCode.JQuery.Program = $d.declare("DuoCode.JQuery.Program", System.Object, 0, $asm, function($t, $p) {
    $t.RunJQuery = function Program_RunJQuery() {
        var a = $.fn.init("div");
        for (var $i = 0, $length = a.toArray().length; $i != $length; $i++) {
            var item = a.toArray()[$i];
            console.log($.fn.init(item).selector);
            item.innerHTML = "<p>asdasd</p>";
        }

        DuoCode.JQuery.JQueryObjectExtensions.FadeOut(a, System.TimeSpan.FromSeconds(4), null).html("LOL");
    };
    $t.RunAjax = function Program_RunAjax() {
        var el = $.fn.init(document.getElementById("content"));

        var options = (function() {
            var $obj = new (DuoCode.JQuery.AjaxSettings$2(HTMLElement, DuoCode.JQuery.HtmlElementDeserializer).ctor)();
            $obj.set_Method(1 /* Method.GET */);
            $obj.set_Url("http://localhost:19308");
            $obj.set_BeforeSend($d.delegate(function(jqXhr, ajaxSettings) {
                el.fadeOut(0);
            }, this));
            $obj.set_OnSuccess($d.delegate(function(htmlElement, textStatus, jqXhr) {
                console.log(htmlElement);
            }, this));
            return $obj;
        }).call(this);

        $.ajax(HTMLElement, DuoCode.JQuery.HtmlElementDeserializer, options);
    };
    $t.RunAjaxJsonp = function Program_RunAjaxJsonp() {
        var input = $d.as(document.getElementById("inp"), HTMLInputElement);
        var button = document.getElementById("btn");

        button.onclick = $d.delegate(function(event) {
            var options = (function() {
                var $obj = new (DuoCode.JQuery.JsonpOptions$1(DuoCode.JQuery.Md5HashInfo).ctor)();
                $obj.set_Url(input == null ? String.Empty : input.value || String.Empty);
                $obj.set_OnSuccess($d.delegate(function(json) {
                    json.Foo();
                }, this));
                return $obj;
            }).call(this);

            DuoCode.JQuery.Jsonp.Request(DuoCode.JQuery.Md5HashInfo, options);

            return null;
        }, this);
    };
});
return $asm;
})();
//# sourceMappingURL=DuoCode.JQuery.js.map
