//
// Mindbox.PostAddress.Example, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//
// Generated by DuoCode Compiler 0.3.878.0 BETA
//
(function Mindbox_PostAddress_Example() {
"use strict";
var $asm = {
    fullName: "Mindbox.PostAddress.Example",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() {
        return [new System.Reflection.AssemblyTitleAttribute.ctor("HelloDuoCode"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), 
            new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), 
            new System.Reflection.AssemblyProductAttribute.ctor("HelloDuoCode"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9  2015"), 
            new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), 
            new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), 
            new DuoCode.Runtime.CompilerAttribute.ctor("0.3.878.0 BETA")];
    }
};
var $g = (typeof(global) !== "undefined" ? global : window);
var Mindbox = $g.Mindbox = $g.Mindbox || {};
Mindbox.PostAddress = Mindbox.PostAddress || {};
Mindbox.PostAddress.Example = Mindbox.PostAddress.Example || {};
var $d = DuoCode.Runtime;
$d.$assemblies["Mindbox.PostAddress.Example"] = $asm;
Mindbox.PostAddress.Example.Program = $d.declare("Mindbox.PostAddress.Example.Program", System.Object, 
    0, $asm, function($t, $p) {
        $t.Run = function Program_Run() {
            Mindbox.PostAddress.PostAddress.Initialize((function() {
                var $obj = new Mindbox.PostAddress.PostAddressOptions.ctor();
                $obj.set_Debug(true);
                return $obj;
            }).call(this));
        };
    });
return $asm;
})();
//# sourceMappingURL=Mindbox.PostAddress.Example.js.map
