//
// HelloDuoCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//
// Generated by DuoCode Compiler 0.3.878.0 BETA
//
(function HelloDuoCode() {
"use strict";
var $asm = {
    fullName: "HelloDuoCode",
    anonymousTypes: [],
    types: [],
    $getAttrs: function() {
        return [new System.Reflection.AssemblyTitleAttribute.ctor("HelloDuoCode"), new System.Reflection.AssemblyDescriptionAttribute.ctor(""), 
            new System.Reflection.AssemblyConfigurationAttribute.ctor(""), new System.Reflection.AssemblyCompanyAttribute.ctor(""), 
            new System.Reflection.AssemblyProductAttribute.ctor("HelloDuoCode"), new System.Reflection.AssemblyCopyrightAttribute.ctor("Copyright \xA9  2015"), 
            new System.Reflection.AssemblyTrademarkAttribute.ctor(""), new System.Reflection.AssemblyCultureAttribute.ctor(""), 
            new System.Reflection.AssemblyVersionAttribute.ctor("1.0.0.0"), new System.Reflection.AssemblyFileVersionAttribute.ctor("1.0.0.0"), 
            new DuoCode.Runtime.CompilerAttribute.ctor("0.3.878.0 BETA")];
    }
};
var $g = (typeof(global) !== "undefined" ? global : window);
var HelloDuoCode = $g.HelloDuoCode = $g.HelloDuoCode || {};
HelloDuoCode.Extensions = HelloDuoCode.Extensions || {};
var $d = DuoCode.Runtime;
$d.$assemblies["HelloDuoCode"] = $asm;
HelloDuoCode.Color = $d.declare("HelloDuoCode.Color", null, 62, $asm, function($t, $p) {
    $t.cctor = function() {
        $t.Violet = new HelloDuoCode.Color.ctor$2(204, 50, 206);
        $t.White = new HelloDuoCode.Color.ctor$1(1, 1, 1);
        $t.Grey = new HelloDuoCode.Color.ctor$1(0.5, 0.5, 0.5);
        $t.Black = new HelloDuoCode.Color.ctor$1(0, 0, 0);
        $t.Background = $t().Black;
        $t.DefaultColor = $t().Black;
    };
    $t.ctor = function Color() {
        this.R = 0;
        this.G = 0;
        this.B = 0;
    };
    $t.ctor.prototype = $p;
    $t.ctor$1 = function Color(r, g, b) {
        this.R = r;
        this.G = g;
        this.B = b;
    };
    $t.ctor$1.prototype = $p;
    $t.ctor$2 = function Color(r, g, b) {
        $t.ctor$1.call(this, HelloDuoCode.Color.FromByte(r), HelloDuoCode.Color.FromByte(g), HelloDuoCode.Color.FromByte(b));
    };
    $t.ctor$2.prototype = $p;
    $t.op_Multiply$1 = function Color_op_Multiply$1(k, v) {
        return new HelloDuoCode.Color.ctor$1(k * v.R, k * v.G, k * v.B);
    };
    $t.op_Addition = function Color_op_Addition(v1, v2) {
        return new HelloDuoCode.Color.ctor$1(v1.R + v2.R, v1.G + v2.G, v1.B + v2.B);
    };
    $t.op_Multiply = function Color_op_Multiply(v1, v2) {
        return new HelloDuoCode.Color.ctor$1(v1.R * v2.R, v1.G * v2.G, v1.B * v2.B);
    };
    $t.ToByte = function Color_ToByte(value) {
        value = value > 1 ? 1 : value;
        return (System.Math.Floor$1(value * 255 /* Byte.MaxValue */) | 0);
    };
    $t.FromByte = function Color_FromByte(value) {
        if (value > 255 /* Byte.MaxValue */)
            value = 255 /* Byte.MaxValue */;

        if (value < 0)
            value = 0;

        return value / 255 /* Byte.MaxValue */;
    };
    $p.ToString = function Color_ToString() {
        return String.Format("rgb({0},{1},{2})", $d.array(System.Object, [HelloDuoCode.Color.ToByte(this.R), 
            HelloDuoCode.Color.ToByte(this.G), HelloDuoCode.Color.ToByte(this.B)]));
    };
});
HelloDuoCode.Extensions.CssStyleDeclarationExtensions = $d.declare("HelloDuoCode.Extensions.CssStyleDeclarationExtensions", 
    System.Object, 0, $asm, function($t, $p) {
        $t.AsDouble = function CssStyleDeclarationExtensions_AsDouble(source, getter) {
            return getter(source) * 1;
        };
        $t.AsInt32 = function CssStyleDeclarationExtensions_AsInt32(source, getter) {
            return getter(source) * 1;
        };
    });
HelloDuoCode.Extensions.HTMLElementExtensions = $d.declare("HelloDuoCode.Extensions.HTMLElementExtensions", 
    System.Object, 0, $asm, function($t, $p) {
        $t.cctor = function() {
            $t.TimeBetweenSteps = 40;
        };
        $t.Fade = function HTMLElementExtensions_Fade(element, fadingTime, initialOpacity) {
            if (element.style.opacity <= 0 || fadingTime.get_TotalMilliseconds() <= 0.01) {
                element.style.display = "none";
                return;
            }

            var shadeStep = initialOpacity / (fadingTime.get_TotalMilliseconds() / 40 /* HTMLElementExtensions.TimeBetweenSteps */);

            element.style.opacity = (HelloDuoCode.Extensions.CssStyleDeclarationExtensions.AsDouble(element.style, 
                $d.delegate(function(s) {
                    return s.opacity;
                }, this)) - shadeStep).ToString();

            window.setTimeout(($d.delegate(function() {
                HelloDuoCode.Extensions.HTMLElementExtensions.Fade(element, fadingTime, initialOpacity);
            }, this)), 40 /* HTMLElementExtensions.TimeBetweenSteps */);
        };
        $t.Show = function HTMLElementExtensions_Show(element, fadingTime, initialOpacity, display) {
            if (element.style.opacity <= 0) {
                element.style.opacity = "0";
                element.style.display = display || "block";
            }

            if (element.style.opacity >= 1 || fadingTime.get_TotalMilliseconds() <= 0.01)
                return;

            var shadeStep = (1 - initialOpacity) / (fadingTime.get_TotalMilliseconds() / 40 /* HTMLElementExtensions.TimeBetweenSteps */);

            // BUG
            element.style.opacity = (shadeStep + HelloDuoCode.Extensions.CssStyleDeclarationExtensions.AsDouble(element.style, 
                $d.delegate(function(s) {
                    return s.opacity;
                }, this))).ToString();

            window.setTimeout(($d.delegate(function() {
                HelloDuoCode.Extensions.HTMLElementExtensions.Show(element, fadingTime, initialOpacity, 
                    null);
            }, this)), 40 /* HTMLElementExtensions.TimeBetweenSteps */);
        };
    });
HelloDuoCode.JQueryObject = $d.declare("HelloDuoCode.JQueryObject", System.Collections.Generic.List$1(HTMLElement), 
    0, $asm, function($t, $p) {
        $t.$intfs = function() { return [System.Collections.Generic.IList$1(HTMLElement), System.Collections.Generic.ICollection$1(HTMLElement), System.Collections.Generic.IReadOnlyList$1(HTMLElement), System.Collections.Generic.IReadOnlyCollection$1(HTMLElement), System.Collections.Generic.IEnumerable$1(HTMLElement), System.Collections.IList, System.Collections.ICollection, System.Collections.IEnumerable]; };
        $t.ctor = function JQueryObject() {
            $t.$baseType.ctor.call(this);
        };
        $t.ctor.prototype = $p;
        $t.ctor$2 = function JQueryObject(elements) {
            $t.ctor.call(this);
            var $iter = elements;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                this.Add(element);
            }
        };
        $t.ctor$2.prototype = $p;
        $t.ctor$1 = function JQueryObject(elements) {
            $t.ctor$2.call(this, System.Linq.Enumerable.ToList(HTMLElement, elements));
        };
        $t.ctor$1.prototype = $p;
        $p.Css = function JQueryObject_Css(setter) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                setter(element.style);
            }

            return this;
        };
        $p.Attr$1 = function JQueryObject_Attr(attributeName, valueBuilder) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                var value = element.getAttribute(attributeName);
                element.setAttribute(attributeName, valueBuilder(value));
            }

            return this;
        };
        $p.Attr$2 = function JQueryObject_Attr(attributeName, value) {
            return this.Attr$1(attributeName, $d.delegate(function(v) {
                return value;
            }, this));
        };
        $p.Attr = function JQueryObject_Attr(attributeName) {
            return System.Linq.Enumerable.Any(HTMLElement, this) ? this.get_Item(0).getAttribute(attributeName) : null;
        };
        $p.AddClass = function JQueryObject_AddClass(className) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                if (!element.classList.contains(className))
                    element.classList.add(className);
            }

            return this;
        };
        $p.RemoveClass = function JQueryObject_RemoveClass(className) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                if (element.classList.contains(className))
                    element.classList.remove(className);
            }

            return this;
        };
        $p.ToggleClass = function JQueryObject_ToggleClass(className) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                if (element.classList.contains(className))
                    element.classList.remove(className);
                else
                    element.classList.add(className);
            }

            return this;
        };
        $p.WithClass = function JQueryObject_WithClass(className) {
            return new HelloDuoCode.JQueryObject.ctor$2(System.Linq.Enumerable.Where(HTMLElement, this, 
                $d.delegate(function(e) {
                    return e.classList.contains(className);
                }, this)));
        };
        $p.WithoutClass = function JQueryObject_WithoutClass(className) {
            return new HelloDuoCode.JQueryObject.ctor$2(System.Linq.Enumerable.Where(HTMLElement, this, 
                $d.delegate(function(e) {
                    return !e.classList.contains(className);
                }, this)));
        };
        $p.AnyHasClass = function JQueryObject_AnyHasClass(className) {
            return System.Linq.Enumerable.Any$1(HTMLElement, this, $d.delegate(function(e) {
                return e.classList.contains(className);
            }, this));
        };
        $p.AllHasClass = function JQueryObject_AllHasClass(className) {
            return System.Linq.Enumerable.All(HTMLElement, this, $d.delegate(function(e) {
                return e.classList.contains(className);
            }, this));
        };
        $p.AnyDontHasClass = function JQueryObject_AnyDontHasClass(className) {
            return !this.AllHasClass(className);
        };
        $p.AllDontHasClass = function JQueryObject_AllDontHasClass(className) {
            return !this.AnyHasClass(className);
        };
        $p.Fade$1 = function JQueryObject_Fade(fadingTimeInMilliseconds) {
            return this.Fade(System.TimeSpan.FromMilliseconds(fadingTimeInMilliseconds));
        };
        $p.Fade = function JQueryObject_Fade(fadingTime) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                element.style.opacity = element.style.opacity || "1";
                HelloDuoCode.Extensions.HTMLElementExtensions.Fade(element, fadingTime, element.style.opacity);
            }

            return this;
        };
        $p.Show$1 = function JQueryObject_Show(showingTimeInMilliseconds, display) {
            return this.Show(System.TimeSpan.FromMilliseconds(showingTimeInMilliseconds), null);
        };
        $p.Show = function JQueryObject_Show(showingTime, display) {
            var $iter = this;
            var $enumerator = $iter.System$Collections$IEnumerable$GetEnumerator();
            while ($enumerator.System$Collections$IEnumerator$MoveNext()) {
                var element = $enumerator.System$Collections$IEnumerator$get_Current();
                element.style.opacity = element.style.opacity || "0";
                HelloDuoCode.Extensions.HTMLElementExtensions.Show(element, showingTime, element.style.opacity, 
                    display);
            }

            return this;
        };
    });
HelloDuoCode.JQuery = $d.declare("HelloDuoCode.JQuery", System.Object, 0, $asm, function($t, $p) {
    $t.cctor = function() {
        $t.Jquery = null;
        $t().Jquery = (window).jQuery;

        if ($t().Jquery == null)
            throw new System.InvalidOperationException.ctor$1("jQuery is not loaded");
    };
    $t.Get$1 = function JQuery_Get(selector) {
        var elements = $t().Jquery(selector);

        var result = new HelloDuoCode.JQueryObject.ctor();
        for (var $i = 0, $length = elements.length; $i != $length; $i++) {
            var element = elements[$i];
            result.Add(element);
        }

        return result;
    };
    $t.Get = function JQuery_Get(htmlElements) {
        return new HelloDuoCode.JQueryObject.ctor$1(htmlElements);
    };
});
HelloDuoCode.Program = $d.declare("HelloDuoCode.Program", System.Object, 0, $asm, function($t, $p) {
    $t.Run = function Program_Run() {
        var el = document.getElementById("content");
        var greeter = new HelloDuoCode.Program.Greeter.ctor(el);
        greeter.Start();

        var z = HelloDuoCode.JQuery.Get$1("div").WithoutClass("a").Show$1(10000, null);

        console.log(z.AnyHasClass("a"));
        console.log(z.AllHasClass("a"));
        console.log(z.AnyDontHasClass("a"));
        console.log(z.AllDontHasClass("a"));
    };
});
HelloDuoCode.Program.Greeter = $d.declare("Greeter", System.Object, 0, HelloDuoCode.Program, function($t, $p) {
    $t.$ator = function() {
        this.span = null;
        this.timerToken = 0;
    };
    $t.ctor = function Greeter(el) {
        $t.$baseType.ctor.call(this);
        this.span = document.createElement("span");
        el.appendChild(this.span);
        this.Tick();
    };
    $t.ctor.prototype = $p;
    $p.Start = function Greeter_Start() {
        this.timerToken = window.setInterval($d.delegate(this.Tick, this), 500);
    };
    $p.Stop = function Greeter_Stop() {
        window.clearTimeout(this.timerToken);
    };
    $p.Tick = function Greeter_Tick() {
        this.span.innerHTML = String.Format("The time is: {0}", $d.array(System.Object, [System.DateTime().get_Now()])); // try to put a breakpoint here
    };
});
return $asm;
})();
//# sourceMappingURL=HelloDuoCode.js.map
